### ISSUE TITLE
`surround-delete` / `surround-change` don't work when point is at the surrounding

### ISSUE THREAD

**Issue by ckruse** [mkleehammer/surround#1]
For example given the text `(foo)`. When the point is at the opening brace and I call `surround-delete` or `surround-change`, I only get a message: `surround--find-char-nestable: Did not find (`

This is true for `(`, `[` and `{`, but it *does* work for `"` and `'`.

**Comment by mkleehammer** [comment]
Thanks for reporting.  I'm not sure how I hadn't noticed - I guess I'm usually deep in a set when I need this.

**Comment by ckruse** [comment]
Yes, it works, thank you very much!
